### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by drvladb** [ashutoshtiwari13/Motion-Detector#1]
When using python3 this error was encountered:
Traceback (most recent call last):
  File "plotting.py", line 1, in <module>
    from motion_detector import df
  File "/Users/vlad/Documents/pythonwork/toolsForCar/mksh/basic-motion-detection/Motion-Detector/motion_detector.py", line 25, in <module>
    (_,cnts,_)=cv2.findContours(thresh_frame.copy(),cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by drvladb** [comment]
A fix would be to modify motion_detector.py line 25 from: 
(_,cnts,_)=cv2.findContours(thresh_frame.copy(),cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
to:
(cnts,_)=cv2.findContours(thresh_frame.copy(),cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
